### PR TITLE
Added Game state machine as an object. fixed some pong issues.

### PR DESCRIPTION
**Pull request by mishafarms**
I have made some changes to pong. The ball is now solid. The ball travels slower. The angle is reduced
if it is too large so we don't bounce 5 times getting to the other side.
Changed the countdown to be a series of smaller rings.

### CODE REVIEW

**Comment by dskvr** [comment]
:+1: Let's merge this one first, as mine will have conflicts.

**Comment by mishafarms** [comment]
Maybe you need to get the latest node. 
http://thisdavej.com/upgrading-to-more-recent-versions-of-node-js-on-the-raspberry-pi/

     Michael

**Comment by dskvr** [comment]
@mishafarms This will require a Node upgrade?

**Comment by mishafarms** [comment]
Not the changes we made. But I think the Raspberry Pi ships with an 
older node.js and I think we need a later one. I couldn't
  get nodegit to install without upgrading.

Michael

**Pull request merged**
